# Generated by Django 3.1.2 on 2020-11-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_post'),
        ('web', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
    ]
