# Generated by Django 3.1.2 on 2020-11-12 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201111_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='id_admin',
            field=models.ForeignKey(blank=True, db_column='id_admin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.administrador'),
        ),
        migrations.AddField(
            model_name='login',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.cliente'),
        ),
        migrations.AddField(
            model_name='login',
            name='id_prof',
            field=models.ForeignKey(blank=True, db_column='id_prof', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.profesional'),
        ),
        migrations.AddField(
            model_name='login',
            name='last_login',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='is_admin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='is_cliente',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='is_prof',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='login',
            table=None,
        ),
    ]
