# Generated by Django 3.1.2 on 2020-11-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_merge_20201104_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
