# Generated by Django 3.1.3 on 2020-11-28 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201111_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accidente',
            fields=[
                ('id_accidente', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.CharField(blank=True, max_length=20, null=True)),
                ('lugar_accidente', models.CharField(blank=True, max_length=200, null=True)),
                ('trabajo_habitual', models.BooleanField(blank=True, null=True)),
                ('tiene_experiencia', models.BooleanField(blank=True, null=True)),
                ('tarea_autorizacion', models.BooleanField(blank=True, null=True)),
                ('desc_lesion', models.CharField(blank=True, max_length=500, null=True)),
                ('grado_lesion', models.CharField(blank=True, max_length=500, null=True)),
                ('contingencia', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'accidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActividadMejora',
            fields=[
                ('id_actividad', models.FloatField(primary_key=True, serialize=False)),
                ('origen', models.CharField(blank=True, max_length=30, null=True)),
                ('actividad', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
                ('evidencia_texto', models.CharField(blank=True, max_length=1000, null=True)),
                ('evidencia_imagen', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividad_mejora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=60, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('respondido', models.BooleanField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsesoriaAccidente',
            fields=[
                ('id_servicio', models.OneToOneField(db_column='id_servicio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='web.servicio')),
                ('inspeccion_lugar_accidente', models.BooleanField(blank=True, null=True)),
                ('verificar_contrato_accidentado', models.BooleanField(blank=True, null=True)),
                ('planifica_capacitacion_riesgos', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsesoriaFiscalizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_fiscalizacion', models.DateField(blank=True, null=True)),
                ('detalle_evento', models.CharField(blank=True, max_length=2000, null=True)),
                ('juicio', models.BooleanField(blank=True, null=True)),
                ('conversacion_fiscalizador', models.BooleanField(blank=True, null=True)),
                ('evidenciar_documentacion', models.BooleanField(blank=True, null=True)),
                ('contingencia', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'asesoria_fiscalizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnteFiscalizador',
            fields=[
                ('id_ente_fiscalizador', models.FloatField(primary_key=True, serialize=False)),
                ('ente_fiscalizador', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ente_fiscalizador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id_estado_solicitud', models.FloatField(primary_key=True, serialize=False)),
                ('estado_solicitud', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'estado_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('descripcion', models.TextField(default='No descripción')),
                ('pk_relacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SituacionActual',
            fields=[
                ('id_situacion', models.FloatField(primary_key=True, serialize=False)),
                ('situacion_actual', models.CharField(blank=True, max_length=1000, null=True)),
                ('propuesta_general', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'situacion_actual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.FloatField(primary_key=True, serialize=False)),
                ('id_profesional', models.CharField(blank=True, max_length=10, null=True)),
                ('detalle', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('hora_creacion', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCapacitacion',
            fields=[
                ('id_tipo_capacitacion', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_capacitacion', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad_tematica', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'tipo_capacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id_tipo_solicitud', models.FloatField(primary_key=True, serialize=False)),
                ('tipo_solicitud', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tipo_solicitud',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='login',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Asesoria',
        ),
    ]
