# Generated by Django 3.1.2 on 2020-11-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('checklist', models.CharField(blank=True, max_length=250, null=True)),
                ('resultado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'checklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoServicio',
            fields=[
                ('id_estado_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estado_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.IntegerField()),
                ('visita', models.IntegerField()),
                ('llamadas', models.IntegerField()),
                ('capacitacion', models.IntegerField()),
                ('asesoria', models.IntegerField()),
                ('modif_lista_chequeo', models.IntegerField()),
                ('actualizacion_docs', models.IntegerField()),
            ],
            options={
                'db_table': 'precio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubtipoServicio',
            fields=[
                ('id_subtipo_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'subtipo_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id_tipo_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_servicio',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='llamada',
            name='id_ticket',
        ),
        migrations.DeleteModel(
            name='Emergencia',
        ),
        migrations.DeleteModel(
            name='Llamada',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
